name = "qr-redirect-worker"
main = "src/index.js"
compatibility_date = "2025-07-03"

[vars]
RATE_LIMIT     = "10"
RATE_WINDOW    = "3600"

[triggers]
crons = ["0 15 * * *"]

[[kv_namespaces]]
binding = "REDIRECT_KV"
id      = "78af36e9eedd423fad55186c46943aca"
